"""initial schema

Revision ID: 7a37239fb318
Revises: 
Create Date: 2026-04-18 01:30:13.250114
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a37239fb318'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_event_created', 'audit_log', ['event_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_audit_user_created', 'audit_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('chat_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_chat_session_user', 'chat_session', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('memory_entry',
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_index('ix_memory_embedding', 'memory_entry', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memory_user', 'memory_entry', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('oauth_token',
    sa.Column('oauth_token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('access_token_ct', sa.LargeBinary(), nullable=False),
    sa.Column('access_token_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_ct', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('oauth_token_id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_account_id', name='uq_oauth_token_user_provider')
    )
    op.create_index('ix_oauth_token_user', 'oauth_token', ['user_id', 'provider'], unique=False)
    op.create_table('pending_confirmation',
    sa.Column('confirmation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','expired')", name='ck_pending_conf_status'),
    sa.PrimaryKeyConstraint('confirmation_id')
    )
    op.create_index('ix_pending_conf_user', 'pending_confirmation', ['user_id', 'status'], unique=False)
    op.create_table('reminder',
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('schedule_kind', sa.String(), nullable=False),
    sa.Column('schedule_expr', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("created_by IN ('user','agent')", name='ck_reminder_created_by'),
    sa.CheckConstraint("schedule_kind IN ('once','cron','interval')", name='ck_reminder_schedule_kind'),
    sa.CheckConstraint("status IN ('active','paused','cancelled')", name='ck_reminder_status'),
    sa.PrimaryKeyConstraint('reminder_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_reminder_user_status', 'reminder', ['user_id', 'status'], unique=False)
    op.create_table('user_profile',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_profile_last_synced', 'user_profile', ['last_synced_at'], unique=False)
    op.create_table('chat_message',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('turn_context', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','model','tool','system')", name='ck_chat_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_chat_message_session_created', 'chat_message', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_chat_message_user_created', 'chat_message', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_message_user_created', table_name='chat_message')
    op.drop_index('ix_chat_message_session_created', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_user_profile_last_synced', table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index('ix_reminder_user_status', table_name='reminder')
    op.drop_table('reminder')
    op.drop_index('ix_pending_conf_user', table_name='pending_confirmation')
    op.drop_table('pending_confirmation')
    op.drop_index('ix_oauth_token_user', table_name='oauth_token')
    op.drop_table('oauth_token')
    op.drop_index('ix_memory_user', table_name='memory_entry')
    op.drop_index('ix_memory_embedding', table_name='memory_entry', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memory_entry')
    op.drop_index('ix_chat_session_user', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('ix_audit_user_created', table_name='audit_log')
    op.drop_index('ix_audit_event_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
