/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Chatv2RouteImport } from './routes/chatv2'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthSuccessRouteImport } from './routes/oauth.success'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Chatv2Route = Chatv2RouteImport.update({
  id: '/chatv2',
  path: '/chatv2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatv2': typeof Chatv2Route
  '/login': typeof LoginRoute
  '/themes': typeof ThemesRoute
  '/oauth/success': typeof OauthSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatv2': typeof Chatv2Route
  '/login': typeof LoginRoute
  '/themes': typeof ThemesRoute
  '/oauth/success': typeof OauthSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatv2': typeof Chatv2Route
  '/login': typeof LoginRoute
  '/themes': typeof ThemesRoute
  '/oauth/success': typeof OauthSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chatv2' | '/login' | '/themes' | '/oauth/success'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chatv2' | '/login' | '/themes' | '/oauth/success'
  id: '__root__' | '/' | '/chatv2' | '/login' | '/themes' | '/oauth/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Chatv2Route: typeof Chatv2Route
  LoginRoute: typeof LoginRoute
  ThemesRoute: typeof ThemesRoute
  OauthSuccessRoute: typeof OauthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatv2': {
      id: '/chatv2'
      path: '/chatv2'
      fullPath: '/chatv2'
      preLoaderRoute: typeof Chatv2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/success': {
      id: '/oauth/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Chatv2Route: Chatv2Route,
  LoginRoute: LoginRoute,
  ThemesRoute: ThemesRoute,
  OauthSuccessRoute: OauthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
